# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c64de0acd9552cf1336c2fb4ef43d2c5752c1053b1fb710c710e574f77ccd17499e05b358c812f9beacf5a9240cac05268966516deef6cfdaba59d2a6cae5cc8

test:
  secret_key_base: e1a7fab788636a58070074cd173e34a3d290e09611095c5d73e43f0f24de2bcfacc5657cc9c200baf9db2397967b3f57b0ab2b5c68a5797ee6771a5d3c6852bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
